[custom]
; ==================== 1. 过滤机场原始节点 ====================
ex_node_name_regex = (?i)家宽|冷门|重置|剩余|到期|官网|直连|网址|倍率|高倍|(^|[^.\d])(([2-9]\d*|1\d+)(\.\d+)?|1\.[1-9]\d*)(x|倍)

; ==================== 2. 策略组配置 ====================
; --- 自动测速组 ---
custom_proxy_group = 全球自动`url-test`.*`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Rainbow.png`https://www.gstatic.com/generate_204`300`50
custom_proxy_group = 香港自动`url-test`^(?i)(?=[^-]*(-|$)).*(港|hk|hongkong|hong kong|🇭🇰)`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png`https://www.gstatic.com/generate_204`300`50
custom_proxy_group = 台湾自动`url-test`^(?i)(?=[^-]*(-|$)).*(台|tw|taiwan|taipei|🇹🇼)`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png`https://www.gstatic.com/generate_204`300`50
custom_proxy_group = 日本自动`url-test`^(?i)(?=[^-]*(-|$)).*(日|jp|japan|tokyo|🇯🇵)`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png`https://www.gstatic.com/generate_204`300`50
custom_proxy_group = 狮城自动`url-test`^(?i)(?=[^-]*(-|$)).*(新加坡|sg|singapore|🇸🇬|^新(?![线上最]))`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png`https://www.gstatic.com/generate_204`300`50
custom_proxy_group = 美国自动`url-test`^(?i)(?=[^-]*(-|$)).*(美|us|usa|america|united states|🇺🇸)`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png`https://www.gstatic.com/generate_204`300`50
custom_proxy_group = Emby自动`url-test`^(?i)(?=[^-]*(-|$)).*(美|us|usa|america|united states|日|jp|japan|tokyo)`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png`https://www.gstatic.com/generate_204`300`50

custom_proxy_group = 全球手动`select`.*`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Clubhouse.png`

; --- 区域手动选择组 ---
custom_proxy_group = 香港策略`select`香港自动`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Hong_Kong.png`^(?i)(?=[^-]*(-|$)).*(港|hk|hongkong|hong kong|🇭🇰)
custom_proxy_group = 台湾策略`select`台湾自动`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Taiwan.png`^(?i)(?=[^-]*(-|$)).*(台|tw|taiwan|taipei|🇹🇼)
custom_proxy_group = 日本策略`select`日本自动`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Japan.png`^(?i)(?=[^-]*(-|$)).*(日|jp|japan|tokyo|🇯🇵)
custom_proxy_group = 狮城策略`select`狮城自动`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Singapore.png`^(?i)(?=[^-]*(-|$)).*(新加坡|sg|singapore|🇸🇬|^新(?![线上最]))
custom_proxy_group = 美国策略`select`美国自动`https://github.com/Koolson/Qure/raw/master/IconSet/Color/United_States.png`^(?i)(?=[^-]*(-|$)).*(美|us|usa|america|united states|🇺🇸)
custom_proxy_group = Emby策略`select`Emby自动`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Media.png`^(?i)(?=[^-]*(-|$)).*(美|us|usa|america|united states|日|jp|japan|tokyo)

; --- 故障转移组 ---
custom_proxy_group = 故障转移`fallback`^(?i)(?=[^-]*(-|$)).*(港|hk|hongkong|hong kong|🇭🇰|台|tw|taiwan|taipei|🇹🇼|新加坡|sg|singapore|🇸🇬|日|jp|japan|tokyo|🇯🇵|美|us|usa|america|united states|🇺🇸)`https://github.com/Koolson/Qure/raw/master/IconSet/Color/ULB.png`https://www.gstatic.com/generate_204`300`50

; --- 核心业务分流策略组 ---
custom_proxy_group = 广告拦截`select`REJECT`DIRECT`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Reject.png
custom_proxy_group = 即时通讯`select`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`Emby策略`DIRECT`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Telegram_X.png
custom_proxy_group = 社交平台`select`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`Emby策略`DIRECT`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Twitter.png
custom_proxy_group = 人工智能`select`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`Emby策略`DIRECT`https://github.com/Koolson/Qure/raw/master/IconSet/Color/AI.png
custom_proxy_group = Spotify`select`DIRECT`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Spotify.png
custom_proxy_group = EMBY`select`Emby策略`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Emby.png
custom_proxy_group = 国际媒体`select`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`Emby策略`DIRECT`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Streaming.png
custom_proxy_group = 谷歌服务`select`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`Emby策略`DIRECT`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Google_Search.png
custom_proxy_group = 微软服务`select`DIRECT`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Microsoft.png
custom_proxy_group = 苹果服务`select`DIRECT`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Apple_1.png
custom_proxy_group = 国外流量`select`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`Emby策略`DIRECT`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Global.png
custom_proxy_group = 国内流量`select`DIRECT`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`https://github.com/Koolson/Qure/raw/master/IconSet/Color/China.png
custom_proxy_group = 漏网之鱼`select`故障转移`全球手动`香港策略`台湾策略`日本策略`狮城策略`美国策略`Emby策略`DIRECT`https://github.com/Koolson/Qure/raw/master/IconSet/Color/Final.png


; ==================== 3. 规则集 ====================
; 格式：策略组名,behavior,format,URL,interval[,no-resolve]

; 广告拦截（666OS txt）
; 广告拦截
ruleset = 广告拦截,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Tracking.txt,21600
ruleset = 广告拦截,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Advertising.txt,21600

; 直连与私有
ruleset = DIRECT,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Private.txt,21600
ruleset = DIRECT,ipcidr,https://github.com/666OS/rules/raw/release/mihomo/ip/Private.txt,21600,no-resolve
ruleset = DIRECT,classical,https://raw.githubusercontent.com/j6y9c4t9/myclashrule/main/Provider_direct.yaml,21600

; 自定义代理
ruleset = 国外流量,classical,https://raw.githubusercontent.com/j6y9c4t9/myclashrule/main/Provider_proxy.yaml,21600

; 即时通讯
ruleset = 即时通讯,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/TM.txt,21600
ruleset = 即时通讯,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Telegram.txt,21600
ruleset = 即时通讯,ipcidr,https://github.com/666OS/rules/raw/release/mihomo/ip/Telegram.txt,21600,no-resolve

; Spotify
ruleset = Spotify,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Spotify.txt,21600

; 社交平台
ruleset = 社交平台,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/SocialMedia.txt,21600
ruleset = 社交平台,ipcidr,https://github.com/666OS/rules/raw/release/mihomo/ip/SocialMedia.txt,21600,no-resolve

; 人工智能
ruleset = 人工智能,domain,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ai-!cn.list,21600
ruleset = 人工智能,ipcidr,https://raw.githubusercontent.com/666OS/rules/refs/heads/release/mihomo/ip/AI.txt,21600,no-resolve

; 开发服务
ruleset = 国外流量,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Dev.txt,21600

; EMBY 与流媒体
ruleset = EMBY,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Emby.txt,21600
ruleset = EMBY,classical,https://raw.githubusercontent.com/j6y9c4t9/myclashrule/main/Emby_proxy.yaml,21600
ruleset = EMBY,ipcidr,https://github.com/666OS/rules/raw/release/mihomo/ip/Emby.txt,21600,no-resolve
ruleset = 国际媒体,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Streaming.txt,21600
ruleset = 国际媒体,ipcidr,https://github.com/666OS/rules/raw/release/mihomo/ip/Streaming.txt,21600,no-resolve

; 谷歌、微软、苹果
ruleset = 谷歌服务,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Google.txt,21600
ruleset = 谷歌服务,ipcidr,https://github.com/666OS/rules/raw/release/mihomo/ip/Google.txt,21600,no-resolve
ruleset = 微软服务,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Microsoft.txt,21600
ruleset = 苹果服务,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Apple.txt,21600

; 国内外流量
ruleset = 国外流量,domain,https://raw.githubusercontent.com/HenryChiao/MIHOMO_YAMLS/refs/heads/ruleset/meta/domain/gfw.list,21600
ruleset = 国外流量,ipcidr,https://raw.githubusercontent.com/HenryChiao/MIHOMO_YAMLS/refs/heads/ruleset/meta/ipcidr/gfw.list,21600,no-resolve
ruleset = DIRECT,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/Download.txt,21600
ruleset = 国内流量,domain,https://github.com/666OS/rules/raw/release/mihomo/domain/China.txt,21600
ruleset = 国内流量,ipcidr,https://raw.githubusercontent.com/666OS/rules/refs/heads/release/mihomo/ip/China.txt,21600,no-resolve

; 兜底规则
ruleset = MATCH,漏网之鱼

enable_rule_generator=true
overwrite_original_rules=true
